version: '3'

networks:
  balancer: {}

services:
  tests:
    build: ./tests
    links:
    - confd:confd
    - etcd:etcd
    volumes:
    - ./tests/:/app/user/
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - balancer
